# Generated by Django 3.0.8 on 2020-07-14 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qiyou', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
