# Generated by Django 3.0.8 on 2020-07-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qiyou', '0004_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='data',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
