# Generated by Django 3.0.8 on 2020-07-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qiyou', '0005_auto_20200717_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='data1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
