# Generated by Django 3.0.8 on 2020-07-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qiyou', '0006_auto_20200717_0712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_data',
        ),
    ]
