# Generated by Django 3.0.8 on 2020-07-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qiyou', '0007_delete_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=20, null=True)),
                ('data1', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
