# Generated by Django 3.0.8 on 2020-07-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qiyou', '0009_city_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='hot_route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('day_consume', models.CharField(max_length=20)),
                ('schedule', models.CharField(max_length=500)),
                ('scenery', models.CharField(max_length=500)),
            ],
        ),
    ]
