# Generated by Django 3.0.8 on 2020-07-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qiyou', '0010_hot_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_data',
        ),
    ]
