# Generated by Django 3.0.8 on 2020-07-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qiyou', '0018_user_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_data',
        ),
    ]
