# Generated by Django 3.0.8 on 2020-07-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qiyou', '0021_auto_20200720_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
