# Generated by Django 3.0.8 on 2020-07-20 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qiyou', '0023_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
