# Generated by Django 3.0.8 on 2020-07-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qiyou', '0024_delete_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_path', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20, null=True)),
                ('user_route', models.CharField(max_length=500, null=True)),
                ('user_save', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
