# Generated by Django 3.0.8 on 2020-07-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qiyou', '0025_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
