# Generated by Django 3.0.8 on 2020-07-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qiyou', '0027_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hot_route',
            name='scenery',
            field=models.TextField(max_length=500),
        ),
    ]
