# Generated by Django 3.0.8 on 2020-07-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qiyou', '0029_auto_20200721_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_route',
            name='path',
            field=models.TextField(max_length=500),
        ),
    ]
