# Generated by Django 3.0.8 on 2020-07-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qiyou', '0030_auto_20200721_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_route',
            name='link',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city_route',
            name='route_landscape',
            field=models.TextField(max_length=100),
        ),
    ]
